---
galaxy_info:
  role_name: ocp4_days_workload_rhacm
  author: Nate Stephany (nate@redhat.com)
  description: |
    Set up ACM on OpenShift 4.
  license: MIT
  min_ansible_version: 2.9
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - acm
  - rhacm
dependencies: []
